//authentication
export const USER_REGISTRATION = 'USER_REGISTRATION'
export const USER_VERIFICATION = 'USER_VERIFICATION'
export const USER_LOGIN = 'USER_LOGIN'
export const USER_LOGOUT = 'USER_LOGOUT'

//loading
export const LOADING_START = 'LOADING_START'
export const LOADING_END = 'LOADING_END'

//authentication error
export const RESET_ERRORS = 'RESET_ERRORS'
export const WRONG_USERNAME = 'WRONG_USERNAME'
export const WRONG_PASSWORD = 'WRONG_PASSWORD'
export const USERNAME_IS_TAKEN = 'USERNAME_IS_TAKEN'

//video
export const INVALID_VIDEO_URL = 'INVALID_VIDEO_URL'
export const SET_VIDEO_DATA = 'SET_VIDEO_DATA'
export const REMOVE_VIDEO_DATA = 'REMOVE_VIDEO_DATA'

//user
export const LOAD_USER_DATA = 'LOAD_USER_DATA'
export const UPDATE_USER_DATA = 'UPDATE_USER_DATA'
export const CHANGE_USER_STATUS = 'CHANGE_USER_STATUS'
export const LEAVE_WALL_COMMENT = 'LEAVE_WALL_COMMENT'
export const DELETE_WALL_COMMENT = 'DELETE_WALL_COMMENT'
export const USER_AVATAR_CHANGE = 'USER_AVATAR_CHANGE'
export const USER_LIKE_ADDED = 'USER_LIKE_ADDED'
export const FRIEND_REQUEST_SENT = 'FRIEND_REQUEST_SENT'
export const FRIEND_REMOVED = 'FRIEND_REMOVED'
export const FRIEND_REQUEST_ACCEPTED = 'FRIEND_REQUEST_ACCEPTED'
export const FRIEND_REQUEST_DELETED = 'FRIEND_REQUEST_DELETED'
export const VIDEO_ADDED = 'VIDEO_ADDED'


//messages
export const LOAD_USER_MESSAGES = 'LOAD_USER_MESSAGES'
export const UPDATE_USER_MESSAGES = 'UPDATE_USER_MESSAGES'
export const USER_SENT_MESSAGE = 'USER_SENT_MESSAGE'
export const USER_DELETED_MESSAGE = 'USER_DELETED_MESSAGE'

//users
export const GET_ALL_USERS = 'GET_ALL_USERS'


//video-player
export const OPEN_VIDEO_PLAYER = 'OPEN_VIDEO_PLAYER'
export const CLOSE_VIDEO_PLAYER = 'CLOSE_VIDEO_PLAYER'